### ISSUE TITLE
カスタムルールを許容してもらえないでしょうか

### ISSUE THREAD

**Issue by Neos21** [lostandfound/textlint-rule-ja-hiragana-hojodoushi#3]
https://github.com/lostandfound/textlint-rule-ja-hiragana-fukushi における `rulePath` のように、
任意のルールを除外・追加できるように、
`dict/hojodoushi.yml` を外部注入できるようなオプションを用意していただけないでしょうか。

個人的に「致します」のみ使いたい場面があり、オプショナルに制御できれば嬉しいなと思った次第です。

**Comment by lostandfound** [comment]
なるほど了解しました。すみませんが現在それほど手が空いておりませんので少々お時間を頂いてよろしいですか？ あるいはPR出していただければ確認の上mergeします。

**Comment by lostandfound** [comment]
`rulePath` に対応しました。
